Connectoo_CRM/CRM/urls.py
from django.conf.urls import url
from .views import *

app_name = 'CRM'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^schools_table/$', schools_table, name='schools_table'),
    url(r'^classes_table/$', classes_table, name='classes_table'),
    url(r'^classes_per_school/(?P<k_garden_id>[0-9]+)$', classes_per_school, name='classes_per_school'),
    url(r'^children_per_school/(?P<k_garden_id>[0-9]+)$', children_per_school, name='children_per_school'),
    url(r'^children_per_class/(?P<group_id>[0-9]+)$', children_per_class, name='children_per_class'),
    url(r'^reports/$', reports, name='reports'),
    url(r'^staff/$', staff, name='staff'),
    url(r'^staff_table/$', staff_table, name='staff_table'),
    url(r'^attendances/$', attendances, name='attendances'),
    url(r'^contacts/(?P<k_garden_id>[0-9]+)$', contacts, name='contacts'),
    url(r'^gallery/$', gallery, name='gallery'),
    url(r'^gallery_kid/(?P<kid_id>[0-9]+)$', gallery_kid, name='gallery_kid'),
    url(r'^gallery_class/(?P<group_id>[0-9]+)$', gallery_class, name='gallery_class'),
    url(r'^gallery_schools/(?P<k_garden_id>[0-9]+)$', gallery_schools, name='gallery_schools'),
    url(r'^child_profile/(?P<kid_id>[0-9]+)$',child_profile, name='child_profile'),
    url(r'^add_to_album/$', add_to_album, name='add_to_album'),
    url(r'^child_profile_health/(?P<kid_id>[0-9]+)$', child_profile_health, name='child_profile_health'),
    url(r'^child_profile_reports/(?P<kid_id>[0-9]+)$', child_profile_reports, name='child_profile_reports'),
    url(r'^calendar/$', calendar, name='calendar'),
    url(r'^magnet/(?P<group_id>[0-9]+)$', magnet, name='magnet'),
    url(r'^album/$', album, name='album'),
]

Connectoo_CRM/Connectoo_CRM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('CRM.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('Accounts.urls')),
]
# + static(settings.STATIC_URL, document_root = settings.MEDIA_ROOT)

Connectoo_CRM/CRM/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

# import django
# django.setup()
# import os
# import sys

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# from django.contrib.auth.models import AbstractUser
# from django.contrib.auth.models import AnonymousUser
# from django.contrib.auth import get_user_model as user_model
# User = user_model()

# from django.conf import settings
# try:
#     from django.contrib.auth import get_user_model
#     User = settings.AUTH_USER_MODEL
# except ImportError:
#     from django.contrib.auth.models import User


# class User(AbstractUser):
#     pass

class Agendas(models.Model):
    is_awake = models.IntegerField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    agendable_id = models.IntegerField(blank=True, null=True)
    agendable_type = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    report = models.CharField(max_length=255, blank=True, null=True)
    active = models.IntegerField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    poop_id = models.IntegerField(blank=True, null=True)
    lack_id = models.IntegerField(blank=True, null=True)
    food_id = models.IntegerField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    will_be_absent_until = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'agendas'
    
    def __str__(self):
        return self.comment


class Attachments(models.Model):
    file_file_name = models.CharField(max_length=255, blank=True, null=True)
    file_content_type = models.CharField(max_length=255, blank=True, null=True)
    file_file_size = models.IntegerField(blank=True, null=True)
    file_updated_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'attachments'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class BulletinGhosts(models.Model):
    bulletin = models.ForeignKey('Bulletins', models.DO_NOTHING, blank=True, null=True)
    group_ids = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'bulletin_ghosts'


class BulletinGroups(models.Model):
    bulletin = models.ForeignKey('Bulletins', models.DO_NOTHING, blank=True, null=True)
    group = models.ForeignKey('Groups', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'bulletin_groups'


class BulletinLinks(models.Model):
    url = models.CharField(max_length=255, blank=True, null=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image_file_name = models.CharField(max_length=255, blank=True, null=True)
    image_content_type = models.CharField(max_length=255, blank=True, null=True)
    image_file_size = models.IntegerField(blank=True, null=True)
    image_updated_at = models.DateTimeField(blank=True, null=True)
    bulletin = models.ForeignKey('Bulletins', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'bulletin_links'


class BulletinPhotos(models.Model):
    bulletin = models.ForeignKey('Bulletins', models.DO_NOTHING, blank=True, null=True)
    image_file_name = models.CharField(max_length=255, blank=True, null=True)
    image_content_type = models.CharField(max_length=255, blank=True, null=True)
    image_file_size = models.IntegerField(blank=True, null=True)
    image_updated_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'bulletin_photos'


class Bulletins(models.Model):
    text = models.TextField(blank=True, null=True)
    k_garden = models.ForeignKey('KGardens', models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    link = models.CharField(max_length=255, blank=True, null=True)
    creator_id = models.IntegerField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    updater_id = models.IntegerField(blank=True, null=True)
    deleter_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'bulletins'


class Contacts(models.Model):
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)
    contact_profile_id = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    cell_phone = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    contact_pic_file_name = models.CharField(max_length=255, blank=True, null=True)
    contact_pic_content_type = models.CharField(max_length=255, blank=True, null=True)
    contact_pic_file_size = models.IntegerField(blank=True, null=True)
    contact_pic_updated_at = models.DateTimeField(blank=True, null=True)
    user_id = models.IntegerField(blank=True, null=True)
    contact_title = models.CharField(max_length=255, blank=True, null=True)
    relative_id = models.IntegerField(blank=True, null=True)
    kid = models.ForeignKey('Kids', models.DO_NOTHING, blank=True, null=True)
    registered_user = models.IntegerField(blank=True, null=True)
    creator_id = models.IntegerField(blank=True, null=True)
    visible = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'contacts'


class Conversions(models.Model):
    from_id = models.IntegerField(blank=True, null=True)
    to_id = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    isnew = models.IntegerField(db_column='isNew', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'conversions'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)

Connectoo_CRM/CRM/templates/CRM/classes.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Classes {% endblock%}

<!-- ********************** BEGIN CSS LINKS ********************** -->
{%block PAGE_LEVEL_CSS_PLUGINS%}
<link href="{% static '/global/plugins/cubeportfolio/css/cubeportfolio.css' %}" rel="stylesheet" type="text/css" />

{%endblock%}

{%block THEME_GLOBAL_STYLES%}
<link href="{% static '/global/css/components.min.css' %}" rel="stylesheet" id="style_components" type="text/css" />
<link href="{% static '/global/css/plugins.min.css' %}" rel="stylesheet" type="text/css" />
{%endblock%}

{%block PAGE_LEVEL_STYLES%}
<link href="{% static '/pages/css/portfolio.min.css' %}" rel="stylesheet" type="text/css" />
{%endblock%}

{%block THEME_LAYOUT_STYLES%}
<link href="{% static '/layouts/layout/css/layout.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static '/layouts/layout/css/themes/darkblue.min.css' %}" rel="stylesheet" type="text/css" id="style_color" />
<link href="{% static '/layouts/layout/css/custom.min.css' %}" rel="stylesheet" type="text/css" />
{%endblock%}
<!-- ********************** END CSS LINKS ********************** -->


{% block section %}
    <li>
        <a href="{% url 'CRM:classes_per_school' school.id %}">School</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="#">Classes</a>
    </li>
{% endblock%}

{% block info %}
<h1>{{school.name}}
<a style="float: right" class="btn btn-primary" href="{% url 'CRM:gallery_schools' school.id %}" role="button"><i class="fa fa-picture-o"></i> School Gallery</a>
</h1>
<h5 style="padding-left: 20px; padding-top: 10px;"><i class="icon-home"></i> {{school.street}}</h5>
<h5 style="padding-left: 20px"><i class="fa fa-phone"></i> {{school.phone}}</h5>
{% endblock%}

{% block page-title %}
Classes
{% endblock%}

{% block content %}
    <div class="row">
        {% for c in classes %}
        {% if forloop.counter0|divisibleby:'4' %}
        </div>
        <div class="row">
        {% endif %}
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <a href="{% url 'CRM:children_per_class' c.id %}">
                <div class="portlet light portlet-fit bordered">
                    <div style="margin: 0" class="portlet-title">
                            <i class=" icon-layers font-green"></i>
                            <span class="caption-subject font-green bold uppercase">{{c.name}}</span>
                            <div class="caption-desc font-grey-cascade">{{school.name}}</div>
                    </div>
                </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock%}

<!-- ********************** BEGIN JS LINKS ********************** -->
{%block PAGE_LEVEL_JS_PLUGINS%}
<script src="{% static '/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
<script src="{% static '/global/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
{%endblock%}

{%block THEME_GLOBAL_SCRIPTS%}
<script src="{% static '/global/scripts/app.min.js' %}" type="text/javascript"></script>
{%endblock%}

{%block PAGE_LEVEL_SCRIPTS%}
<script src="{% static '/apps/scripts/todo-2.min.js' %}" type="text/javascript"></script>
{%endblock%}

{%block THEME_LAYOUT_SCRIPTS%}
<script src="{% static '/layouts/layout/scripts/layout.min.js' %}" type="text/javascript"></script>
<script src="{% static '/layouts/layout/scripts/demo.min.js' %}" type="text/javascript"></script>
<script src="{% static '/layouts/global/scripts/quick-sidebar.min.js' %}" type="text/javascript"></script>
{%endblock%}
<!-- ********************** END JS LINKS ********************** -->

Connectoo_CRM/CRM/templates/CRM/classes_table.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Classes {% endblock%}

<!-- ********************** BEGIN CSS LINKS ********************** -->
{%block PAGE_LEVEL_CSS_PLUGINS%}
<link href="{% static '/global/plugins/datatables/datatables.min.css'%}" rel="stylesheet" type="text/css" />
<link href="{% static '/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'%}" rel="stylesheet" type="text/css" />
{%endblock%}

{%block THEME_GLOBAL_STYLES%}
<link href="{% static '/global/css/components.min.css'%}" rel="stylesheet" id="style_components" type="text/css" />
<link href="{% static '/global/css/plugins.min.css'%}" rel="stylesheet" type="text/css" />
{%endblock%}

{%block THEME_LAYOUT_STYLES%}
<link href="{% static '/layouts/layout/css/layout.min.css'%}" rel="stylesheet" type="text/css" />
<link href="{% static '/layouts/layout/css/themes/darkblue.min.css'%}" rel="stylesheet" type="text/css" id="style_color" />
<link href="{% static '/layouts/layout/css/custom.min.css'%}" rel="stylesheet" type="text/css" />
{%endblock%}

{%block CUSTOM_CSS%}
<link href="{% static '/custom/css/attendances.css'%}" rel="stylesheet" type="text/css" />
{%endblock%}
<!-- ********************** END CSS LINKS ********************** -->

{% block section %}
Classes
{% endblock%}

{% block page-title %}
Classes
{% endblock%}

{% block content %}

    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1" style="white-space: nowrap;overflow: scroll;">
        <thead>
            <tr>
                <th>#</th>
                <th>School</th>
                <th>Class</th>
                <th>Teacher</th>
                <th>Kids</th>
            </tr>
        </thead>
        <tbody>
            {% for c in classes %}
            <tr class="odd gradeX">
                <td>{{forloop.counter}}</td>
                <td><a href="{% url 'CRM:classes_per_school' c.k_garden.id %}">{{c.k_garden.name}}</a></td>
                <td><a href="{% url 'CRM:children_per_class' c.id %}">{{c.name}}</a></td>
                <td>Staff name</td>
                <td class="center">num of kids</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}
<!-- ********************** BEGIN JS LINKS ********************** -->
{%block PAGE_LEVEL_JS_PLUGINS%}
<script src="{% static '/global/plugins/datatables/datatables.min.js'%}" type="text/javascript"></script>
<script src="{% static '/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'%}" type="text/javascript"></script>
{%endblock%}

{%block THEME_GLOBAL_SCRIPTS%}
<script src="{% static '/global/scripts/app.min.js'%}" type="text/javascript"></script>
{%endblock%}

{%block PAGE_LEVEL_SCRIPTS%}
<script src="{% static '/pages/scripts/table-datatables-managed.min.js'%}" type="text/javascript"></script>
{%endblock%}

{%block THEME_LAYOUT_SCRIPTS%}
<script src="{% static '/layouts/layout/scripts/layout.min.js'%}" type="text/javascript"></script>
<script src="{% static '/layouts/layout/scripts/demo.min.js'%}" type="text/javascript"></script>
<script src="{% static '/layouts/global/scripts/quick-sidebar.min.js'%}" type="text/javascript"></script>
{%endblock%}

Connectoo_CRM/CRM/templates/CRM/gallery_kid.html
{% extends "gallery_template.html" %}
{% load staticfiles %}

{% block section %}
    <li>
        <a href="{% url 'CRM:classes_per_school' kid.group.k_garden.id %}">School</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="{% url 'CRM:children_per_class' kid.group.id %}">Class</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a>Gallery</a>
    </li>
{% endblock%}

{% block page-title %}
Photos of &nbsp; <a href="{% url 'CRM:child_profile' kid.id %}">Erez</a>
{% endblock%}

{% block content %}
    
    {% comment %}{% if kid_pics %}{% endcomment %}
    
    <div id="js-grid-lightbox-gallery" class="cbp">

        {% comment %}
        {% for p in kid_pics %}
            <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="https://connectoo.co.il/uploads/kid_photos/{{p.id}}/original/data.jpg">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <div class="cbp-l-caption-title">{{ p.event }}</div>
                                <div class="cbp-l-caption-desc">{{ p.created_at }}</div>
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        
        {% for p in tagged_pics %}
            <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="https://connectoo.co.il/uploads/pictures/{{p.id}}/original/data.jpg">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <div class="cbp-l-caption-title">{{ p.event }}</div>
                                <div class="cbp-l-caption-desc">{{ p.date.date }}</div>
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        {% endcomment %}

            <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/1.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/2.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        
        <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/3.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/4.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/5.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/6.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/7.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/8.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/9.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
    <div class="cbp-item web-design graphic print motion">
                <a class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <img src="{% static '/media/child/10.jpg' %}">
                    </div>
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <button type="button" class="btn btn-circle green btn-sm album">Add to Album</button>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
    </div>
        {% comment %}{% else %}
            <h3 style="padding-left: 30px;">Nothing to show...</h3>
        {% endif %}{% endcomment %}

{% endblock%}

Connectoo_CRM/CRM/templates/CRM/my_album.html
{% extends "gallery_template.html" %}

{% load staticfiles%}

{%block CUSTOM_JAVASCRIPT%}
<script src="{% static '/custom/js/populate_album.js' %}" type="text/javascript"></script>
{%endblock%}

{% block section %}
    <li>
        <a href="#">School</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="#">Class</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="#">Gallery</a>
    </li>
{% endblock%}


{% block page-title %}
<h3 style="height: 35px; position: relative">
    My Album
    <a style="position: absolute; right: 0" class="btn btn-primary" href="#" role="button">Send to print</a>
    <a id="delete-album" style="position: absolute; right: 120px" class="btn btn-danger" href="{% url 'CRM:album' %}" role="button">Delete album</a>
</h3>
{% endblock%}

{% block content %}

{% endblock%}